namespace Component
{
    interface IDefault
    {
        Int32 DefaultProperty { get; };
    }

    interface INonDefault
    {
        Int32 NonDefaultProperty { get; };
    }

    [default_interface]
    runtimeclass Class
    {
        Class();
        Int32 Int32Property;
        Object ObjectProperty;
        String StringProperty;

        Object NewObject();
    }
}
